### ISSUE TITLE
Run sample proj

### ISSUE THREAD

**Issue by samukbg** [slavavdovichenko/MediaLibDemos3x#34]
Hi, i'm trying to run the MediaLibDemos.xcodeproj, but i'm getting the following warnings and errors:

ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/libspeex-1.2rc1/lib/libspeex.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/libspeex-1.2rc1/lib/libspeex.a (3 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavdevice.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavdevice.a (3 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavutil.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavutil.a (3 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/MediaLibiOS/MediaLibiOS.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/MediaLibiOS/MediaLibiOS.a (2 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libswscale.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libswscale.a (3 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libswresample.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libswresample.a (3 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/libspeex-1.2rc1/lib/libspeexdsp.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/libspeex-1.2rc1/lib/libspeexdsp.a (3 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavformat.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavformat.a (3 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavfilter.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavfilter.a (3 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/libx264-r2409/lib/libx264.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/libx264-r2409/lib/libx264.a (3 slices)
ld: warning: ignoring file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavcodec.a, missing required architecture i386 in file /Users/samukbg/Downloads/MediaLibDemos/lib/ffmpeg-2.2.1/lib/libavcodec.a (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_BroadcastStreamClient", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I've already added all libraries from the Readme file, and the following "Valid Architectures" in "Build Settings": "i386 armv6 armv7 armv7s".

Thanks in advance,
Sam.

**Comment by slavavdovichenko** [comment]
Hi Sam,

You have to build the project for device, not for simulator. This lib doesn't have the simulator architectures (i386, x86_64) at all.

**Comment by slavavdovichenko** [comment]
the libs were updated for iOS9, and now they work with simulator

**Comment by samukbg** [comment]
Thanks @slavavdovichenko i'm closing this issue
