### ISSUE TITLE
ENABLE_BITCODE

### ISSUE THREAD

**Issue by serpro** [slavavdovichenko/MediaLibDemos3x#35]
According to this: https://news.ycombinator.com/item?id=9682671

in the new xcode 7 Beta 3. All the libraries need to contain bitcode. Is there anything I can do with this project to enable it?

I'm trying to run the examples in iOS 9 with xcode 7 Beta 3.

**Comment by slavavdovichenko** [comment]
libs were updated for iOS9

**Comment by serpro** [comment]
Thanks!
