### ISSUE TITLE
player cannot connect server

### ISSUE THREAD

**Issue by hans00** [slavavdovichenko/MediaLibDemos3x#50]
I use your demo play RTMP audio stream,
My server is red5 with speex codec
Console only output : 

```
RTMPStreamPlayer[2166:775667] ******************************************** connectControl: host = rtmp://18k.myqnapcloud.com/giantview/23/
------------------------------------------------------
rtmp_buffer=0
rtmp_conn=
-----------------------------------------------------
```

and no more outpot

**Comment by slavavdovichenko** [comment]
You should use @"rtmp://18k.myqnapcloud.com:1935/giantview/23/"

**Comment by hans00** [comment]
I added ":1935" , but also.

**Comment by slavavdovichenko** [comment]
It works for me with your endpoint.
Set 
    hostTextField.text = @"rtmp://18k.myqnapcloud.com:1935/giantview/23";
in RTMPStreamPublisher and RTMPStreamPlayer targets and try again.

**Comment by hans00** [comment]
Audio and video in one stream is normal.
But only audio stream, it no output any sound.
And when I connect multiple stream in one application, the audio publish stream will no voice.
Our project is conference room, so we should separate connect multiple audio and video.

**Comment by hans00** [comment]
Can your lib connect only audio stream ?

**Comment by slavavdovichenko** [comment]
I have made some fix - so download the fixed libs and you will publish
"only audio" stream:

-(void)doConnect {

    upstream = [[BroadcastStreamClient alloc] initOnlyAudio:hostURL];

    upstream.delegate = self;

     [upstream stream:streamName publishType:PUBLISH_LIVE];

}

But if you wish also playback this stream - you must use only AAC codec.

**Comment by kvkvkvk** [comment]
Hi slavavdovichenko,

Can you please provide a working URL for hostTextField and steamTextField for both SteamPublisher and SteamPlayer? My company is very interested to integrate this lib into our commercial project. Please suggest. 

Thank you.

**Comment by slavavdovichenko** [comment]
Hi,

Give me your email - i'll send the endpoint, my email:
slavav@themidnightcoders.com
