### ISSUE TITLE
audio noises

### ISSUE THREAD

**Issue by rizkyazhary** [slavavdovichenko/MediaLibDemos3x#55]
Hello, i already try your sample project. I use RTMPStreamPlayer. The video is run well. But the audio is full of noise. i think there is the problem with audio decoder. can you fix it or you have suggest for me? Sorry for my bad English. thank you

this is my stream video and audio format from streaming server.
`<meta>`
`<video>`
`<width>212</width>`
`<height>160</height>`
`<frame_rate>30</frame_rate>`
`<codec>H264</codec>`
`<profile>High</profile>`
`<compat>0</compat>`
`<level>2.0</level>`
`</video>`
`<audio>`
`<codec>AAC</codec>`
`<profile>LC</profile>`
`<channels>2</channels>`
`<sample_rate>44100</sample_rate>`
`</audio>`
`</meta>`

**Comment by rizkyazhary** [comment]
i run in simulator

**Comment by slavavdovichenko** [comment]
Hi,

Maybe in your cause you should use
    decoder.isRealTime = NO;

See this sample - https://drive.google.com/file/d/0B3yyaWhA4ib0ZS1lZmFMbGJONkk/view?usp=sharing
It demonstrates how you could play the different streams at the same time.

**Comment by rizkyazhary** [comment]
Now i hear the sound, but it like in cave. any other suggest for me? thank you

**Comment by rizkyazhary** [comment]
this is the log form xcode,

`Input #0, flv, from 'rtmp://192.168.0.38:1935/live/kasep':`
 ` Metadata:`
    `Server          : NGINX RTMP (github.com/arut/nginx-rtmp-module)`
    `displayWidth    : 212`
    `displayHeight   : 160`
    `fps             : 30`
    `profile         : `
    `level           : `
  `Duration: 00:00:00.00, start: 225.001000, bitrate: N/A`
    `Stream #0.0: Video: h264 (High), yuv420p, 212x160, 1024 kb/s, 30 fps, 1k tbn, 60 tbc`
    `Stream #0.1: Audio: aac, 44100 Hz, mono, fltp`

**Comment by slavavdovichenko** [comment]
This issue is fixed - please, try again

**Comment by rizkyazhary** [comment]
thank you so much,

really help my day :D
