### ISSUE TITLE
RTMP player - output volume too low

### ISSUE THREAD

**Issue by srmds** [slavavdovichenko/MediaLibDemos3x#59]
The output volume of the RTMP player is too low, how can i change the output volume (set to unity gain),programmatically)?

I've tested it on both iPhone 5 and iPhone 6 physical devices,both devices have low volume gain.
Note: the volume on the physical device is set to max.

Thanks in advance.

**Comment by slavavdovichenko** [comment]
This issue is fixed - you can try again

**Comment by srmds** [comment]
@slavavdovichenko Great, will pull the new changes! Thanks for the quick response and your effort!
