### ISSUE TITLE
Low Audio with Real Device

### ISSUE THREAD

**Issue by rizkyazhary** [slavavdovichenko/MediaLibDemos3x#68]
hello again, thank you so much for your help that fix my last issue..

right now i use your latest lib. I found some new issue when i use real device, then volume is really low, that anything i can set programmatically for the volume?

sorry for bad english

thanks

**Comment by rizkyazhary** [comment]
I am using the MPMediaDecoder

**Comment by slavavdovichenko** [comment]
Hi,

Use         
[MPMediaData routeAudioToSpeaker];
for example,
-(void)stateChanged:(id)sender state:(MPMediaStreamState)state description:(NSString *)description {
    
    switch (state) {
         .......
        case STREAM_PLAYING: {
              ....
            [MPMediaData routeAudioToSpeaker];
                break;
            }
             ....
}

**Comment by rizkyazhary** [comment]
work like a charm :D

thank you so much

**Comment by jageshaamit** [comment]
Hello slavavdovichenko,
I am uncomment this line [MPMediaData routeAudioToSpeaker]; but still not able to play to speaker in ipad ?
