### ISSUE TITLE
Audio Volume 

### ISSUE THREAD

**Issue by TomerGlick** [slavavdovichenko/MediaLibDemos3x#75]
Hi, I'm using the MPMediaDecoder to play a live stream from wowza server, used your demo as an example, the volume I get from the stream is too low with my volume on the phone is maximum volume.
Is there anything to do to "boost" the volume ? 

- (void) doConnect {
    decoder = [[MPMediaDecoder alloc] initWithView:previewView];
    decoder.delegate = self;
    decoder.isRealTime = YES;
    decoder.orientation = UIImageOrientationUp;
    [decoder setupStream:strURLWithRoomID];
}

**Comment by slavavdovichenko** [comment]
You could route audio to speaker - simply uncomment [this line](https://github.com/slavavdovichenko/MediaLibDemos3x/blob/master/RTMPStreamPlayer/ViewController.m#L217) in Player sample
