### ISSUE TITLE
audio stream not found in playback

### ISSUE THREAD

**Issue by tranquan** [slavavdovichenko/MediaLibDemos3x#9]
Hi, I run your example on my iphone (iOS 8.1), and broadcast a live video to my server (using Adobe Flash). It's broadcast ok, but when I playback using ffplay. I only get video stream, the audio stream not found or not parsed.

This is ffplay output:
Input #0, flv, from 'rtmp://<server_address>:1935/live/test99004':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: flv1, yuv420p, 352x288, 30 tbr, 1k tbn, 1k tbc
    Stream #0:1: Data: none
 178.93 M-V: -0.011 fd=  24 aq=    0KB vq=    0KB sq=    0B f=27/27

But when I stop broadcasting and download record file from server and open it, the audio can play. It's stil there but I don't understand why in live streaming, I can't see the audio.
Do I need to send metadata about audio codec, etc before broadcasting.
Thank you

**Comment by kvrraviteja** [comment]
Hi,

I am running the MediaLibDemo in iPad. 

This demo works only in portrait orientation. I changed / set the property "orientation" in  "BroadcastStreamClient" class (as shown below).  

orientation = AVCaptureVideoOrientationLandscapeLeft;
 [upstream setVideoOrientation:orientation];

Orientation of captured video is always portrait irrespective of the above property i.e., even the orientation of the device is in Landscape, the video is still captured in Portrait. 

Could some one help me on how i can make this work in Landscape mode as well. 

Thanks in advance.

**Comment by slavavdovichenko** [comment]
Hi SONAL,

I've checked all demo samples - all work fine for me.
Can you clone the last release and try again?

**Comment by slavavdovichenko** [comment]
Hi kvrraviteja,

The orientation of the publisher sets the orientation of the publishing stream, not the orientation of the preview view (which is used by AVCaptureVideoPreviewLayer, and rotates with a device rotation - this is its functionality).

You can try the different publisher orientations on the device, and check the changing of  the stream orientation on the player (for example, on Wowza Flash RTMP Player - http://www.wowza.com/resources/3.5.0/examples/LiveVideoStreaming/FlashRTMPPlayer/player.html).

**Comment by rameshbabu2020** [comment]
Hi,

I run you examples.Its working fine for ios.But while trying with cross platforms like android to ios.I am not getting voice clearly.Can you give me the suggestion about this.Bot are encoding audio in AAC format only

**Comment by reenaphilip** [comment]
I am developing an application using the MediaLib for publishing the video to server. Application supports  landscape orientation only. When running the app, the video is showing the portrait only. I am not able to set it as landscape. But the stream orientation at the server is correct when setting the publisher orientation. Please help me to fix this issue.
